// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteAccount(arg1) {
  return window['go']['api']['Accounts']['DeleteAccount'](arg1);
}

export function GetAccount(arg1) {
  return window['go']['api']['Accounts']['GetAccount'](arg1);
}

export function GetAccounts() {
  return window['go']['api']['Accounts']['GetAccounts']();
}

export function GetActive() {
  return window['go']['api']['Accounts']['GetActive']();
}

export function HasCredentials() {
  return window['go']['api']['Accounts']['HasCredentials']();
}

export function SaveAccount(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['api']['Accounts']['SaveAccount'](arg1, arg2, arg3, arg4, arg5);
}

export function SetActive(arg1) {
  return window['go']['api']['Accounts']['SetActive'](arg1);
}

export function Startup(arg1) {
  return window['go']['api']['Accounts']['Startup'](arg1);
}
