// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {reddit} from '../models';
import {context} from '../models';

export function Nuke(arg1:reddit.NukeRequest):Promise<reddit.NukeResult>;

export function Startup(arg1:context.Context):Promise<void>;
