// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Nuke(arg1) {
  return window['go']['api']['Reddit']['Nuke'](arg1);
}

export function Startup(arg1) {
  return window['go']['api']['Reddit']['Startup'](arg1);
}
