// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteSchedule(arg1) {
  return window['go']['api']['Scheduler']['DeleteSchedule'](arg1);
}

export function GetScheduleByUsername(arg1) {
  return window['go']['api']['Scheduler']['GetScheduleByUsername'](arg1);
}

export function GetSchedules() {
  return window['go']['api']['Scheduler']['GetSchedules']();
}

export function SaveSchedule(arg1) {
  return window['go']['api']['Scheduler']['SaveSchedule'](arg1);
}

export function Startup(arg1) {
  return window['go']['api']['Scheduler']['Startup'](arg1);
}
