// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';

export function DeleteAccount(arg1:string):Promise<void>;

export function GetAccount(arg1:string):Promise<models.Account>;

export function GetAccounts():Promise<Array<models.Account>>;

export function GetActive():Promise<models.Account>;

export function HasCredentials():Promise<boolean>;

export function SaveAccount(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<void>;

export function SetActive(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
