// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteAccount(arg1) {
  return window['go']['accounts']['Service']['DeleteAccount'](arg1);
}

export function GetAccount(arg1) {
  return window['go']['accounts']['Service']['GetAccount'](arg1);
}

export function GetAccounts() {
  return window['go']['accounts']['Service']['GetAccounts']();
}

export function GetActive() {
  return window['go']['accounts']['Service']['GetActive']();
}

export function HasCredentials() {
  return window['go']['accounts']['Service']['HasCredentials']();
}

export function SaveAccount(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['accounts']['Service']['SaveAccount'](arg1, arg2, arg3, arg4, arg5);
}

export function SetActive(arg1) {
  return window['go']['accounts']['Service']['SetActive'](arg1);
}

export function Startup(arg1) {
  return window['go']['accounts']['Service']['Startup'](arg1);
}
