// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {reddit} from '../models';
import {accounts} from '../models';

export function Nuke(arg1:reddit.NukeRequest):Promise<void>;

export function SetAccountService(arg1:accounts.Service):Promise<void>;
