// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Nuke(arg1) {
  return window['go']['main']['App']['Nuke'](arg1);
}

export function SetAccountService(arg1) {
  return window['go']['main']['App']['SetAccountService'](arg1);
}
